#!/usr/bin/env bash

set -Eeuo pipefail

# shellcheck source=tests/test-helper.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/test-helper.sh"

for required_file in \
  README.md \
  CONTRIBUTING.md \
  SECURITY.md \
  CHANGELOG.md \
  RELEASE_NOTES.md \
  docs/getting-started.md \
  docs/benchmark-format.md \
  docs/scoring.md \
  docs/comparison-methodology.md \
  docs/agent-adapters.md \
  docs/result-format.md \
  docs/architecture.md \
  docs/security.md \
  examples/README.md; do
  assert_file "$TEST_ROOT/$required_file"
done

grep -q 'Test your AI context like you test your code' "$TEST_ROOT/README.md" || fail "README is missing the primary tagline"
grep -q 'agentbench.sh compare BASELINE CANDIDATE' "$TEST_ROOT/README.md" || fail "README is missing the compare CLI contract"
grep -q 'AgentBench v0.1.0' "$TEST_ROOT/RELEASE_NOTES.md" || fail "release notes version is incorrect"
grep -q 'Generated by scripts/build-standalone.sh' "$TEST_ROOT/agentbench.sh" || fail "standalone runner is not generated"
"$TEST_ROOT/install.sh" --help >/dev/null

printf 'ok - release documentation and standalone references are complete\n'
